/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eletrotech;

import dao.ProdutoDao;
import javax.swing.JOptionPane;
import model.Produto;

/**
 *
 * @author Aluno_Manha
 */
public class Agendamentos extends javax.swing.JFrame {
    /**
     * Creates new form Agendamentos
     */
    public Agendamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        Valo = new javax.swing.JLabel();
        Plano = new javax.swing.JLabel();
        Pagamento = new javax.swing.JLabel();
        Datas = new javax.swing.JLabel();
        Horas = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        IdadeFun = new javax.swing.JLabel();
        NomeFun = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        FormacaoFun = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        IdFun = new javax.swing.JLabel();
        NomeCli = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        CepCli = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        TeleCli = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        l13 = new javax.swing.JLabel();
        Id1 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        Valo1 = new javax.swing.JLabel();
        Plano1 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        Horas1 = new javax.swing.JLabel();
        Datas1 = new javax.swing.JLabel();
        l25 = new javax.swing.JLabel();
        Pagamento1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        IdFun1 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        IdadeFun1 = new javax.swing.JLabel();
        NomeFun1 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        FormacaoFun1 = new javax.swing.JLabel();
        TeleCli1 = new javax.swing.JLabel();
        CepCli1 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        NomeCli1 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eletrotech/tomada (5).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jPanel2.setBackground(new java.awt.Color(141, 32, 54));

        l1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));

        l7.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l7.setForeground(new java.awt.Color(255, 255, 255));

        l6.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));

        l8.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l8.setForeground(new java.awt.Color(255, 255, 255));

        l26.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l26.setForeground(new java.awt.Color(255, 255, 255));

        l5.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));

        Id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Id.setForeground(new java.awt.Color(255, 255, 255));

        Valo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Valo.setForeground(new java.awt.Color(255, 255, 255));

        Plano.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Plano.setForeground(new java.awt.Color(255, 255, 255));

        Pagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pagamento.setForeground(new java.awt.Color(255, 255, 255));

        Datas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Datas.setForeground(new java.awt.Color(255, 255, 255));

        Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Horas.setForeground(new java.awt.Color(255, 255, 255));

        l9.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l9.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        IdadeFun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdadeFun.setForeground(new java.awt.Color(255, 255, 255));

        NomeFun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeFun.setForeground(new java.awt.Color(255, 255, 255));

        l10.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l10.setForeground(new java.awt.Color(255, 255, 255));

        l11.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l11.setForeground(new java.awt.Color(255, 255, 255));

        FormacaoFun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FormacaoFun.setForeground(new java.awt.Color(255, 255, 255));

        l12.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l12.setForeground(new java.awt.Color(255, 255, 255));

        IdFun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdFun.setForeground(new java.awt.Color(255, 255, 255));

        NomeCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeCli.setForeground(new java.awt.Color(255, 255, 255));

        l2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));

        CepCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CepCli.setForeground(new java.awt.Color(255, 255, 255));

        l3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));

        TeleCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TeleCli.setForeground(new java.awt.Color(255, 255, 255));

        l4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));

        jButton3.setText("Marcar como concluido");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Id))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeCli))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CepCli))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TeleCli)))
                .addGap(121, 121, 121)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Datas))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Plano))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Valo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Horas)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IdadeFun))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NomeFun)
                                        .addGap(132, 132, 132)
                                        .addComponent(l12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FormacaoFun)))
                                .addContainerGap(783, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IdFun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pagamento)
                                .addGap(46, 46, 46))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(70, 70, 70))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(l7)
                                .addComponent(Horas))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l5)
                                    .addComponent(Datas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l6)
                                    .addComponent(Plano))
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(l4)
                                .addComponent(TeleCli))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(l8)
                                .addComponent(Valo))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l1)
                            .addComponent(l26)
                            .addComponent(Id)
                            .addComponent(Pagamento)
                            .addComponent(l9)
                            .addComponent(IdFun))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l2)
                                    .addComponent(NomeCli))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l3)
                                    .addComponent(CepCli))
                                .addGap(94, 94, 94))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l10)
                                    .addComponent(NomeFun)
                                    .addComponent(l12)
                                    .addComponent(FormacaoFun))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l11)
                                    .addComponent(IdadeFun))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18))))))
        );

        jPanel4.setBackground(new java.awt.Color(141, 32, 54));

        l13.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l13.setForeground(new java.awt.Color(255, 255, 255));

        Id1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Id1.setForeground(new java.awt.Color(255, 255, 255));

        l18.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l18.setForeground(new java.awt.Color(255, 255, 255));

        l20.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l20.setForeground(new java.awt.Color(255, 255, 255));

        Valo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Valo1.setForeground(new java.awt.Color(255, 255, 255));

        Plano1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Plano1.setForeground(new java.awt.Color(255, 255, 255));

        l17.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l17.setForeground(new java.awt.Color(255, 255, 255));

        l19.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l19.setForeground(new java.awt.Color(255, 255, 255));

        Horas1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Horas1.setForeground(new java.awt.Color(255, 255, 255));

        Datas1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Datas1.setForeground(new java.awt.Color(255, 255, 255));

        l25.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l25.setForeground(new java.awt.Color(255, 255, 255));

        Pagamento1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pagamento1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        IdFun1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdFun1.setForeground(new java.awt.Color(255, 255, 255));

        l21.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l21.setForeground(new java.awt.Color(255, 255, 255));

        l24.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l24.setForeground(new java.awt.Color(255, 255, 255));

        l23.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l23.setForeground(new java.awt.Color(255, 255, 255));

        IdadeFun1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdadeFun1.setForeground(new java.awt.Color(255, 255, 255));

        NomeFun1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeFun1.setForeground(new java.awt.Color(255, 255, 255));

        l22.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l22.setForeground(new java.awt.Color(255, 255, 255));

        FormacaoFun1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FormacaoFun1.setForeground(new java.awt.Color(255, 255, 255));

        TeleCli1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TeleCli1.setForeground(new java.awt.Color(255, 255, 255));

        CepCli1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CepCli1.setForeground(new java.awt.Color(255, 255, 255));

        l16.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l16.setForeground(new java.awt.Color(255, 255, 255));

        NomeCli1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeCli1.setForeground(new java.awt.Color(255, 255, 255));

        l15.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l15.setForeground(new java.awt.Color(255, 255, 255));

        l14.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l14.setForeground(new java.awt.Color(255, 255, 255));

        jButton4.setText("Marcar como concluido");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Id1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeCli1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CepCli1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TeleCli1)))
                .addGap(115, 115, 115)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Datas1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Plano1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Horas1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Valo1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(l23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IdadeFun1))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(l22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NomeFun1)))
                                .addGap(118, 118, 118)
                                .addComponent(l24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FormacaoFun1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(l21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IdFun1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pagamento1)
                .addGap(49, 49, 49))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l13)
                            .addComponent(Id1)
                            .addComponent(l17)
                            .addComponent(Datas1))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l18)
                                    .addComponent(Plano1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l19)
                                    .addComponent(Horas1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l20)
                                    .addComponent(Valo1)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(l16)
                                            .addComponent(TeleCli1)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(l14)
                                            .addComponent(NomeCli1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(l15)
                                            .addComponent(CepCli1))))
                                .addGap(0, 48, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l21)
                            .addComponent(IdFun1)
                            .addComponent(l25)
                            .addComponent(Pagamento1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l22)
                            .addComponent(NomeFun1)
                            .addComponent(l24)
                            .addComponent(FormacaoFun1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l23)
                            .addComponent(IdadeFun1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );

        jButton1.setText("voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            Eletrotech frame = new Eletrotech();

            frame.show();
            frame.setVisible(true);
            dispose();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,
                    "Numero Invalido!!!",
                    "Errorrrr",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ProdutoDao produtodao = new ProdutoDao();
        Produto produto = new Produto();
        int cont = 1;

        l1.setText("Id do Cliente: ");
        l2.setText("Nome do Cliente: ");
        l3.setText("Cep: ");
        l4.setText("Telefone: ");
        l5.setText("Data: ");
        l6.setText("Tipo de Plano: ");
        l7.setText("Horario Marcado: ");
        l8.setText("Valor: ");
        l9.setText("Id do Funcionario: ");
        l10.setText("Nome: ");
        l11.setText("Idade: ");
        l12.setText("Formacao: ");
        l13.setText("Id do Cliente: ");
        l14.setText("Nome do Cliente: ");
        l15.setText("Cep: ");
        l16.setText("Telefone: ");
        l17.setText("Data: ");
        l18.setText("Tipo de Plano: ");
        l19.setText("Horario Marcado: ");
        l20.setText("Valor: ");
        l21.setText("Id do Funcionario: ");
        l22.setText("Nome: ");
        l23.setText("Idade: ");
        l24.setText("Formacao: ");
        l25.setText("Pago: ");
        l26.setText("Pago: ");

        for (Produto c : produtodao.ListarProduto()) {
            Id.setText("" + c.getId());
            Plano.setText("" + c.getPlanos());
            Valo.setText("" + c.getValor());
            Datas.setText("" + c.getDate());
            Horas.setText("" + c.getHora());
            Pagamento.setText("" + c.getPago());
        }
        
        for( Produto c : produtodao.ListarProduto2()) {
            Id1.setText("" + c.getId());
            Plano1.setText("" + c.getPlanos());
            Valo1.setText("" + c.getValor());
            Datas1.setText("" + c.getDate());
            Horas1.setText("" + c.getHora());
            Pagamento1.setText("" + c.getPago());
        }
        
        for( Produto c : produtodao.ListarFun()) {
            IdFun.setText("" + c.getIdFun());
            NomeFun.setText("" + c.getNomeFun());
            IdadeFun.setText("" + c.getIdadeFun());
            FormacaoFun.setText("" + c.getFormacao());
        }
        
        for( Produto c : produtodao.ListarFun2()) {
            IdFun1.setText("" + c.getIdFun());
            NomeFun1.setText("" + c.getNomeFun());
            IdadeFun1.setText("" + c.getIdadeFun());
            FormacaoFun1.setText("" + c.getFormacao());
        }
        
        for( Produto c : produtodao.ListarUsu()) {
            NomeCli.setText("" + c.getNomeUsu());
            TeleCli.setText("" + c.getTeleUsu());
            CepCli.setText("" + c.getCepUsu());
            
        }
        
        for( Produto c : produtodao.ListarUsu2()) {
            NomeCli1.setText("" + c.getNomeUsu());
            TeleCli1.setText("" + c.getTeleUsu());
            CepCli1.setText("" + c.getCepUsu());
            
        }
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         l1.setText("");
        l2.setText("");
        l3.setText("");
        l4.setText("");
        l5.setText("");
        l6.setText("");
        l7.setText("");
        l8.setText("");
        l9.setText("");
        l10.setText("");
        l11.setText("");
        l12.setText("");
        
        l26.setText("");
        
        
            Id.setText("");
            Plano.setText("");
            Valo.setText("");
            Datas.setText("");
            Horas.setText("");
            Pagamento.setText("");
        
        
        
            
        
        
       
            IdFun.setText("");
            NomeFun.setText("");
            IdadeFun.setText("");
            FormacaoFun.setText("");
        
        
       
            
        
        
       
            NomeCli.setText("");
            TeleCli.setText("");
            CepCli.setText("");
            
        
        
       
            
            
            
            
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        l13.setText("");
        l14.setText("");
        l15.setText("");
        l16.setText("");
        l17.setText("");
        l18.setText("");
        l19.setText("");
        l20.setText("");
        l21.setText("");
        l22.setText("");
        l23.setText("");
        l24.setText("");
        l25.setText("");
        
        Id1.setText("");
            Plano1.setText("");
            Valo1.setText("");
            Datas1.setText("");
            Horas1.setText("");
            Pagamento1.setText("");
            
            IdFun1.setText("");
            NomeFun1.setText("");
            IdadeFun1.setText("");
            FormacaoFun1.setText("");
            
            NomeCli1.setText("");
            TeleCli1.setText("");
            CepCli1.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agendamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CepCli;
    private javax.swing.JLabel CepCli1;
    private javax.swing.JLabel Datas;
    private javax.swing.JLabel Datas1;
    private javax.swing.JLabel FormacaoFun;
    private javax.swing.JLabel FormacaoFun1;
    private javax.swing.JLabel Horas;
    private javax.swing.JLabel Horas1;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Id1;
    private javax.swing.JLabel IdFun;
    private javax.swing.JLabel IdFun1;
    private javax.swing.JLabel IdadeFun;
    private javax.swing.JLabel IdadeFun1;
    private javax.swing.JLabel NomeCli;
    private javax.swing.JLabel NomeCli1;
    private javax.swing.JLabel NomeFun;
    private javax.swing.JLabel NomeFun1;
    private javax.swing.JLabel Pagamento;
    private javax.swing.JLabel Pagamento1;
    private javax.swing.JLabel Plano;
    private javax.swing.JLabel Plano1;
    private javax.swing.JLabel TeleCli;
    private javax.swing.JLabel TeleCli1;
    private javax.swing.JLabel Valo;
    private javax.swing.JLabel Valo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l24;
    private javax.swing.JLabel l25;
    private javax.swing.JLabel l26;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cont
     */
    
}
