/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eletrotech;


import dao.ProdutoDao;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import model.Produto;

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno_Manha
 */
public class Ordem extends javax.swing.JFrame {

    /**
     * Creates new form ORdem
     */
    public Ordem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        Valo = new javax.swing.JLabel();
        Plano = new javax.swing.JLabel();
        Pagamento = new javax.swing.JLabel();
        Datas = new javax.swing.JLabel();
        Horas = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        IdadeFun = new javax.swing.JLabel();
        NomeFun = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        FormacaoFun = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        IdFun = new javax.swing.JLabel();
        NomeCli = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        CepCli = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        TeleCli = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(141, 32, 54));

        l1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));

        l7.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l7.setForeground(new java.awt.Color(255, 255, 255));

        l6.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));

        l8.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l8.setForeground(new java.awt.Color(255, 255, 255));

        l26.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l26.setForeground(new java.awt.Color(255, 255, 255));

        l5.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));

        Id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Id.setForeground(new java.awt.Color(255, 255, 255));

        Valo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Valo.setForeground(new java.awt.Color(255, 255, 255));

        Plano.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Plano.setForeground(new java.awt.Color(255, 255, 255));

        Pagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pagamento.setForeground(new java.awt.Color(255, 255, 255));

        Datas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Datas.setForeground(new java.awt.Color(255, 255, 255));

        Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Horas.setForeground(new java.awt.Color(255, 255, 255));

        l9.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l9.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        IdadeFun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdadeFun.setForeground(new java.awt.Color(255, 255, 255));

        NomeFun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeFun.setForeground(new java.awt.Color(255, 255, 255));

        l10.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l10.setForeground(new java.awt.Color(255, 255, 255));

        l11.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l11.setForeground(new java.awt.Color(255, 255, 255));

        FormacaoFun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FormacaoFun.setForeground(new java.awt.Color(255, 255, 255));

        l12.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l12.setForeground(new java.awt.Color(255, 255, 255));

        IdFun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdFun.setForeground(new java.awt.Color(255, 255, 255));

        NomeCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeCli.setForeground(new java.awt.Color(255, 255, 255));

        l2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));

        CepCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CepCli.setForeground(new java.awt.Color(255, 255, 255));

        l3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));

        TeleCli.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TeleCli.setForeground(new java.awt.Color(255, 255, 255));

        l4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));

        jButton3.setText("Marcar como concluido");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Id))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeCli))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CepCli))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TeleCli)))
                .addGap(121, 121, 121)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Datas))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(l6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Plano))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Valo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Horas)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IdadeFun))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(l10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NomeFun)
                                        .addGap(132, 132, 132)
                                        .addComponent(l12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FormacaoFun)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IdFun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pagamento)
                                .addGap(46, 46, 46))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(70, 70, 70))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(l7)
                                .addComponent(Horas))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l5)
                                    .addComponent(Datas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l6)
                                    .addComponent(Plano))
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(l4)
                                .addComponent(TeleCli))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(l8)
                                .addComponent(Valo))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l1)
                            .addComponent(l26)
                            .addComponent(Id)
                            .addComponent(Pagamento)
                            .addComponent(l9)
                            .addComponent(IdFun))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l2)
                                    .addComponent(NomeCli))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l3)
                                    .addComponent(CepCli))
                                .addGap(94, 94, 94))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l10)
                                    .addComponent(NomeFun)
                                    .addComponent(l12)
                                    .addComponent(FormacaoFun))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l11)
                                    .addComponent(IdadeFun))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18))))))
        );

        jButton1.setText("voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eletrotech/tomada (5).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(78, 78, 78)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Date dataHoraAtual = new Date();
        String data = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
        String hora = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual);
        
        JOptionPane.showMessageDialog(null,
                    " A Ordem de Serviço foi aceita pelo usuário que está em acesso " + "\nVoce deve cumprir o prazo previsto para evitar possiveis penalidades"
                    + "\nData de registro de chamado: " + data + " Horário: " + hora  ,       
                    "Emissão de O.S",
                    JOptionPane.INFORMATION_MESSAGE);        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            Eletrotech frame = new Eletrotech();

            frame.show();
            frame.setVisible(true);
            dispose();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,
                "Numero Invalido!!!",
                "Errorrrr",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ProdutoDao produtodao = new ProdutoDao();
        Produto produto = new Produto();
        int cont = 1;

        l1.setText("Id do Cliente: ");
        l2.setText("Nome do Cliente: ");
        l3.setText("Cep: ");
        l4.setText("Telefone: ");
        l5.setText("Data: ");
        l6.setText("Tipo de Plano: ");
        l7.setText("Horario Marcado: ");
        l8.setText("Valor: ");
        l9.setText("Id do Funcionario: ");
        l10.setText("Nome: ");
        l11.setText("Idade: ");
        l12.setText("Formacao: ");
    
        l26.setText("Pago: ");

        for (Produto c : produtodao.ListarProduto()) {
            Id.setText("" + c.getId());
            Plano.setText("" + c.getPlanos());
            Valo.setText("" + c.getValor());
            Datas.setText("" + c.getDate());
            Horas.setText("" + c.getHora());
            Pagamento.setText("" + c.getPago());
        }

        

        for( Produto c : produtodao.ListarUsu()) {
            NomeCli.setText("" + c.getNomeUsu());
            TeleCli.setText("" + c.getTeleUsu());
            CepCli.setText("" + c.getCepUsu());

        }

       

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CepCli;
    private javax.swing.JLabel Datas;
    private javax.swing.JLabel FormacaoFun;
    private javax.swing.JLabel Horas;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel IdFun;
    private javax.swing.JLabel IdadeFun;
    private javax.swing.JLabel NomeCli;
    private javax.swing.JLabel NomeFun;
    private javax.swing.JLabel Pagamento;
    private javax.swing.JLabel Plano;
    private javax.swing.JLabel TeleCli;
    private javax.swing.JLabel Valo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l26;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
